---
- hosts: localhost
  vars_files:
    - ./config.yml
    - vars/main.yml

  become: yes
  connection: local
  tasks:

    - include: tasks/common_set.yml

    - include: tasks/install.yml

    - include: tasks/after_install.yml
      tags: after_task

  handlers:
    - include: handlers/main.yml

